# Generated by Django 5.0.14 on 2025-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prod_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="product"),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "Cleat_stud",
                    models.CharField(
                        choices=[
                            ("FG", "Firm Ground"),
                            ("AG", "Artificial Ground"),
                            ("TF", "Turf"),
                        ],
                        default="FG",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
